site_name: "mastodon-finder"
site_url: "https://mastodon-finder.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Mastodon account discovery, enrichment, and LLM-based scoring tool."

repo_url: "https://github.com/matthewdeanmartin/mastodon-finder"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - 'Home': 'index.md'
  - 'Change Log': '../CHANGELOG.md'
